version: "3.8"
services:
  java_app:
    container_name: java_app
    image: tomaslenzi/java_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/todolistspring?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=123456789
    depends_on:
     - java_db

  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: todolistspring
    volumes:
      -  mysql-data:/var/lib/mysql

volumes:
  mysql-data:
